apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cluster-dns
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-cluster-dns
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: {{ .Release.Name }}-cluster-dns
    spec:
      containers:
        - name: cluster-dns
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          env:
            - name: CONFIGMAP_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-cluster-dns
                  key: message
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10

    